<?php


namespace SerasaExperian\Tests;

use PHPUnit\Framework\TestCase;
use SerasaExperian\SerasaExperianProxy;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-25 at 13:16:01.
 */
class SerasaExperianProxyTest extends TestCase {

    /**
     * @var SerasaExperianProxy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = SerasaExperianProxy::getInstance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SerasaExperian\SerasaExperianProxy::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance() {
        $this->assertInstanceOf('SerasaExperian\SerasaExperianProxy', $this->object);
    }

    /**
     * @covers SerasaExperian\SerasaExperianProxy::setHomologacao
     * @todo   Implement testSetHomologacao().
     */
    public function testSetHomologacao() {
        $this->assertClassHasAttribute('homologacao', 'SerasaExperian\SerasaExperianProxy');
    }

    /**
     * @covers SerasaExperian\SerasaExperianProxy::getClient
     * @todo   Implement testGetClient().
     */
    public function testGetClient() {
        $this->assertInstanceOf('SoapClient', $this->object->getClient());
    }

}
